### ISSUE TITLE
Media Gallery Thumbnails are not being displayed for video and audio content

### ISSUE THREAD

**Issue by arthurgr** [netspotau/moodle-mod_mediagallery#13] opened 2017-10-02 15:43 UTC
When upgrading to version 3.3, there seems to be a issue with generating thumbnails for audio and video media. It seems like image media will correctly generate thumbnails since it has image media to fall back on.
![screen shot 2017-10-02 at 9 41 36 am](https://user-images.githubusercontent.com/5983541/31086038-ffe202da-a755-11e7-889f-bb6feb667a19.png)
Any Gallery that contains any media other than a image will break the thumbnail images.
I believe this may be a Moodle issue and not a plug-in issue because of certain files that have changed when updating to version 3.3
Inside of lib/filelib.php the way that $fileicons are generated has changed. 
![screen shot 2017-10-02 at 9 42 05 am](https://user-images.githubusercontent.com/5983541/31086045-06ebae0a-a756-11e7-87d1-252b193bf917.png)
You can see above how thumbnail files were originally referencing png files, but now they are referencing SVG files. When I look at the directory where these images are being stored, I can see they are still being stored as png images, and not SVG images.
Another possible cause is the actual thumbnail upload section. 
![screen shot 2017-10-02 at 9 42 14 am](https://user-images.githubusercontent.com/5983541/31086063-15efb1b2-a756-11e7-90d8-1116ef9982a7.png)
You can see the "Use as a Thumbnail" section. This always will revert to "No" regardless of the media type. The thumbnail upload section also clears out all files.
Please let me know if you need any additional information about this. I appreciate the communities help.
Thanks

**Comment by aolley** [comment] 2017-10-02 23:16
Hi @arthurgr,

I've been able to replicate this. I'll try to have something for this today.

**Comment by arthurgr** [comment] 2017-10-02 23:21
We really appreciate this Aolley!! This is a production bug we are fighting, so any help is greatly appreciated!!! Even if you can point us to where we should be looking in the code, we can help.

Thanks again!!

**Comment by aolley** [comment] 2017-10-02 23:35
It looks like core were going to svg/font-awesome. But then went back to just using the png files (MDL-58356) - but when they did so, they didn't put the send_file line back to using png (the line you pointed out in filelib).

I've opened https://tracker.moodle.org/browse/MDL-60320 for this. I haven't attached a patch just yet - but I think it'll just be switching "svg" to "png" on that line.

Since that section is *just* for generating file icon thumbnails, I can't see it causing issues for anything else.

**Comment by arthurgr** [comment] 2017-10-02 23:49
Hi Adam,
Really appreciate the quick responses!

We thought the same thing as you and we changed it back to .png in the filelib. This seems to only fix the default file image, but not the actual thumbnail image upload.  It seems it always returns default image but we were not able to get the thumbnail image to ever work. 

Thanks!

**Comment by aolley** [comment] 2017-10-02 23:57
As for uploading an image using the thumbnail upload section - there is a fix on the master branch that fixes those being displayed for audio/video (that patch isn't in the version on moodle.org yet).

**Comment by arthurgr** [comment] 2017-10-03 01:26
Thanks so much aolley!! We will be testing this out, your the man!!!!!!

**Comment by aolley** [comment] 2017-10-03 01:29
Do let me know if it fixes the problem you're having - if it does I'll put it into a release on moodle.org.

**Comment by hoz1982** [comment] 2017-10-06 14:01
Hi Adam, thank you for the fix. I have tested it in my 3.3 Moodle, and it seems to solve the issue partially because now the path to the thumbnail is generated(before the fix, the thumbnail path was generated with the file uploaded in the "content" section and not in the "Thumbnail" section), but the file is not stored in that position. I'm working on that, I will post the solution as soon as i find it. 
Thank tou
Alex

**Comment by aolley** [comment] 2017-10-08 23:47
I've done some more testing, with the core fix and the latest master code for mediagallery, I've observed the following so far

* Uploading a video will display the correct file icon
* Uploading a video with a thumbnail image attached gets that image as the thumbnail
* Adding a thumbnail to an existing video item works
* Changing the thumbnail on a video that already had one **does not work**

**Comment by aolley** [comment] 2017-10-08 23:57
@hoz1982 I've just pushed a patch to master which makes the item update process update the thumbnail when you're uploading a new one onto a non-image item.

Does that help with the issue you've run into? If not - could you provide some repro steps that lead to the exact issue you're currently encountering?

**Comment by hoz1982** [comment] 2017-10-09 09:37
Thank you @aolley ! Done some testing and it seems working as described, but I think i found another bug on the mod form and gallery form.

In the mod form, the collection select is not populated with the"standard" and "youtube" values. So, i tried to put a default value by adding $mform->setdefault('mode', 'standard'); to the mod_form.php at line 100.
![schermata 2017-10-09 alle 11 17 56](https://user-images.githubusercontent.com/9212049/31332076-4748b562-ace5-11e7-951a-843774f0a20c.png)

Also, at line 98 of gallery_form.php we have 

if (get_config('mediagallery', 'disablestandardgallery') || $mg->mode != 'standard') {
            unset($opts['standard']);
        }
After commenting the unset it is possible to select the "standard" value, else it shows only the "youtube" one.
Thanks a lot, i'm testing all the stuff and will report as soon as i find the solution to the last point that is still open.
Alex

**Comment by aolley** [comment] 2017-10-09 22:43
Curious, the unset should only happen in two cases:
1) you originally set the gallery as youtube
2) you went into the siteadmin settings and disabled standard galleries outright.

That said - disabling standard shouldn't break editing existing standard galleries. So I'll take a look at that.

**Comment by aolley** [comment] 2017-10-09 23:23
So it looks like you must've ticked the 'disablestandardgallary' option in site admin - which:
1) breaks the mod_form page as you've noted;
2) makes only youtube selectable in the gallery edit page - as designed.

I've put a patch onto master to fix item 1.

**Comment by arthurgr** [comment] 2017-10-10 16:42
Hey Guys, 
Just a fyi, this has fixed my original scenario with the thumbnail images. We have tested this on our end with different media scenarios.

Thanks so much for everyones help!

**Comment by aolley** [comment] 2017-10-20 00:00
MDL-60320 has been integrated and will be in Moodle 3.3.3.

**Comment by aolley** [comment] 2017-10-20 00:00
And I think that's all the outstanding issues with this item.

If I missed something, please leave a comment or open a new bug item. Cheers :)

**Closed by aolley** 2017-10-20 00:00 UTC
